on:
  push:
     branches:
       - main
name: Continous release build web
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#     - uses: actions/setup-java@v1
#       with:
#         java-verison: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-verison: '2.4.0'
    - run: flutter pub get
    - run: |
          flutter build web
          cd build/web
          zip -r web-app.zip .
#     - run: flutter build apk -t lib/main.dart --split-per-abi
    - name: release web
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/web/web-app.zip'
        token: ${{secrets.FLUTTER_TOKEN}}
  
